
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Util classes are awesome!
     avoid_classes_with_only_static_members: false
    
    # Make constructors the first thing in every class
     sort_constructors_first: true

    # Choose wisely, but you don't have to
     prefer_double_quotes: false
     prefer_single_quotes: true
     prefer_const_constructors: false
     avoid_print: false
     directives_ordering: false
